name: SonarCloud Analysis

on:
  # Trigger analysis when pushing to your main branches, and when creating a pull request.
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6.0.2

      - name: Set up JDK 25

        uses: actions/setup-java@v5.2.0
        with:
            java-version: '25'
            distribution: 'temurin'
            java-package: 'jdk'

      - name: Sonar Scan
        uses: sonarsource/sonarqube-scan-action@59db25f34e16620e48ab4bb9e4a5dce155cb5432
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
